kumuluzee:
    dev:
        scan-libraries:
            - KMReportModule1-1.0.jar    
            - KMService1-1.0.jar
    server:
        base-url: http://localhost:80
        http:
            port: 80

